<?php
/**
 * Search Form
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Fetching the searchbar text from the theme options.
$search_text = esc_attr( cyberchimps_get_option( 'searchbar_text' ) );
if( !$search_text )
	$search_text = esc_attr( 'Search &hellip;', 'e-shopper' );
?>
<form method="get"  id="searchform" class="navbar-search input-group" action="<?php echo esc_url( home_url( '/' ) ); ?>" role="search">
	<label class="screen-reader-text" for="s"><?php esc_attr_e( 'Search for:', 'e-shopper' ) ?></label>
	<input type="text" class="search-query form-control" name="s" placeholder="<?php echo $search_text; ?>" />
	<?php
if (e_shopper_is_woocommerce_activated()) 
{
// output all of our Categories
// for more information see http://codex.wordpress.org/Function_Reference/wp_dropdown_categories
$swp_cat_dropdown_args = array(
$deprecated_hierarchical = 0,	
$deprecated_show_uncategorized = 0,	
$deprecated_orderby = '',
//$hide_empty= 0
);
wc_product_dropdown_categories( $swp_cat_dropdown_args );
}
?>
<!--<input type="submit" class="search-submit" value="<?php //echo esc_attr_x( 'Search', 'submit button' ) ?>" /> -->
<div class="search_circle col-lg-1" onclick="jQuery(this).parent('form').submit();"><span class="glyphicon glyphicon-search search1"></span></div>
</form>
<div class="clear"></div>
