<?php
/**
 * Sidebar Home Template
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>
<?php 

if(is_home() || is_front_page())
{

?>
	<div class="container-full-width" id="horizontal-section">
			<div class="container-fluid">
			<div class="container">
				<div id="horizontal-widgets" class="row">
					<div id="horizontal-widget-container" class="col-md-12">
						<div class="row">
						<?php if ( !function_exists('dynamic_sidebar') || !dynamic_sidebar('horizontal_1')) : ?>
						
						<?php endif; ?>
						</div><!-- .row -->
					</div><!-- #horizontal-widget-container -->
				</div><!-- #horizontal-widgets .row  -->
			</div> 	<!-- .container-fluid-->
		</div> 	<!-- .container -->
	</div> 	<!-- #horizontal-section -->

<?php 
}

?>
